-- Obsolete (no-op). This migration originally created the clauses, clause_analysis,
-- detected_issues and policies tables. All four were removed in the schema cleanup:
--   * the analysis result is stored solely on contracts.analysis_json (clauses /
--     clause_analysis / detected_issues were a redundant normalized copy never read for display);
--   * policies were superseded by rule-carried policy text (custom_rules.description).
-- Kept as a no-op so the V2 version number is preserved and re-running stays safe.
