-- Obsolete (no-op). This migration widened summary/recommendation on clause_analysis and
-- explanation/highlighted_text on detected_issues to TEXT. Both tables were removed in the
-- schema cleanup (analysis is stored on contracts.analysis_json). Kept as a no-op to preserve
-- the V4 version number.
